<?php $this->headTitle()->prepend('Log In'); ?>


<style>
    .signup_bar { display: none; }
</style>

<h2 class="page-header" style="text-align: center;">Login</h2>

<div class="row">

    <div class="span6 offset1">

        <div style="border-right: 1px solid #EEEEEE;">
            <?= $this->notice ?>

            <?= $this->login_form ?>

            <br>

            <p style="text-align: center;"><a href="<?= $this->url(array(), 'auth_lost'); ?>">Forgotten your username or password?</a></p>
        </div>

        <style>
            input[type="text"], input[type="password"], textarea, select, .uneditable-input {
                font-size: 20px;
                margin-bottom: 10px;
                padding: 9px;
            }    
            .form-stacked label {
                margin-bottom:3px;
            }
            .control-group {
                margin-bottom: 10px;
            }
            .s_auth {
                display: block;
                float: none;
                margin: 0 auto 25px;
            }
        </style>
    </div>


    <div class="span5">

        <a href="<?= $this->url(array(), 'auth_facebook') ?>" class="fb s_auth span3">
            <div class="ic"></div>
            <span>Login with Facebook</span>
        </a>

        <a href="<?= $this->url(array(), 'auth_twitter') ?>" class="tw s_auth span3">
            <div class="ic"></div>
            <span>Login with Twitter</span>
        </a>

    </div>

</div>