<?php
$this->headTitle()->prepend('404');
?>

<?php
$admin = false;
if (Zend_Auth::getInstance()->getIdentity()) {
    if (Zend_Auth::getInstance()->getIdentity()->role == 'admin') {
        $admin = true;
    }
}

if ('development' == APPLICATION_ENV || $admin):
    ?>

    <h1 class="heading_title">Oops. 404 Error.</h1>
    <h3>Exception information:</h3>
    <p>
        <b>Message:</b> <?= $this->exception->getMessage() ?>
    </p>
    <h3>Request Parameters:</h3>
    <pre><? var_dump($this->request->getParams()) ?></pre>

<? endif ?>
	
    
<h1 class="heading_title">Oops. 404 Error.</h1>

<h3>That's not the page you wanted, but we're not sure what you were looking for.</h3>

<h3>Will you try again, please?</h3>