<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>404 Page not found</title>
</head>
<body>
<div>

<h1>Whoops!</h1>
<h2>We are really sorry but it appears something has broken</h2>
<h3>Please try again, or let us know what's wrong in the <a style="color: #ffffff" href="https://groups.google.com/group/n0tice">n0tice feedback forum</a>.</h3>

<h3><?= $this->message ?></h3>

</div>
<? 
//if ('production' == APPLICATION_ENV):
if ('development' == APPLICATION_ENV): 
?>

<h3>Exception information:</h3>
<p><b>Message:</b> <?= $this->exception->getMessage() ?></p>

<h3>Stack trace:</h3>
<pre><?= $this->exception->getTraceAsString() ?>
  </pre>

<h3>Request Parameters:</h3>
<pre><? var_dump($this->request->getParams()) ?>
  </pre>

<? endif ?>

</body>
</html>
