<?php
/**
 * Default layout, used to render most parts of the application
 *
 * @package frontend_layouts
 * @copyright company
 */
//Configure the title
$this->headTitle()->setSeparator(' - ');
$this->headTitle('company');

//Add generic CSS files
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/master.css');

//Add the ZFDebug Toolbar only if enabled in app.ini
if (Zend_Controller_Front::getInstance()->hasPlugin('ZFDebug_Controller_Plugin_Debug')) {
    $this->headScript()->appendFile($this->baseUrl() . '/js/zfdebug.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/zfdebug.css');
}

//Autoload js files
$this->AutoloadResources();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" /> 
        <meta http-equiv="content-style-type" content="text/css" /> 
        <meta http-equiv="content-script-type" content="text/javascript" />

        <meta name="description" content="">
            <meta name="keywords" content="">

                <link rel="shortcut icon" type="image/ico" href="/images/favicon.png" />

                <?php echo $this->headTitle() . PHP_EOL; ?>
                <?php echo $this->headLink() . PHP_EOL; ?>

                <!--[if lte IE 7]>
                    <link href="/css/ie7.css" media="screen" rel="stylesheet" type="text/css" >
                <![endif]--> 


                </head>
                <body>
                    <div id="page">
                        <div id="header">
                            <div class="wrapper">
                                <?php echo $this->partial('partials/header.phtml'); ?>
                            </div>
                        </div>
                        <div id="content">
                            <div class="wrapper">
                                <?php echo $this->flashMessenger(); ?>
                                <?php echo $this->layout()->content; ?>
                            </div>
                        </div>
                        <div id="footer">
                            <div class="wrapper">
                                <?php echo $this->partial('partials/footer.phtml'); ?>
                            </div>
                        </div>
                    </div>
                    <!-- add the js files -->
                    <?php echo $this->headScript() . PHP_EOL; ?>
                    <?php echo $this->jQuery() . PHP_EOL; ?>
                    <?php if (Zend_Registry::get('IS_PRODUCTION')) : ?>
                        <?php echo $this->partial('partials/ga.phtml'); ?>
                    <?php endif; ?>
                </body>
                </html>