<?php
$this->headTitle()->prepend(ucwords($this->user->user_login));
$this->headTitle()->prepend('Following');
?>

<style>
    .table tr:first-child td { border-top: none; }
</style>

<div class="row"> <!-- Top heading -->
    <div class="span3">

        <?= $this->render('_viewsidebar.phtml') ?>

    </div>

    <div class="span9">

        <h1 style="font-size: 45px; margin-bottom: 0.5em;"><?= $this->user->user_login ?> <small><?= $this->escape($this->user->display_name) ?></small></h1>

        <div class="subnav">
            <ul class="nav nav-pills">
                <li><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_view') ?>">Recent Activity</a></li>
                <li><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_followers') ?>"><b><?= $this->user_followers_count ?></b> followers</a></li>
                <li class="active"><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_following') ?>">following <b><?= $this->total_following_count ?></b></a></li>
                <li><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_noticeboards') ?>"><b><?= $this->user_noticeboard_count ?></b> noticeboards</a></li>
            </ul>
        </div>

        <hr class="space">

        <div class="row">
            <div class="span2">
                <div class="tabbable tabs-left">
                    <ul class="nav nav-tabs" style="width: 100%;font-size: 15px;">
                        <li class="active"><a href="#users" data-toggle="tab"><b><?= $this->user_following_count ?></b> Users</a></li>
                        <li><a href="#noticeboards" data-toggle="tab"><b><?= $this->user_noticeboard_count ?></b> Noticeboards</a></li>
                    </ul>
                </div>
            </div>
            <div class="span7">
                <div class="tab-content">
                    <div class="tab-pane active" id="users">
                        <?php
                        if ($this->users) {
                            $output = array();
                            $output[] = "<table class=\"table user_data\">";
                            $output[] = "<tbody>";
                            $user_model = new User_Model_UserMapper();
                            foreach ($this->users as $user) {
                                $following = false;
                                $user = new User_Model_User($user);
                                $output[] = "<tr>";
                                $output[] = "   <td style=\"width:80px\" class=\"glossy_thumbs\">{$this->profilepicture($user->getUser_login(), 'small', 1)}</td>";
                                $output[] = "   <td><a title=\"{$user->getDisplay_name()}\" href=\"{$this->url(array('id' => $user->getUser_login()), 'user_view')}\" style=\"font-weight:bold;font-size:125%;display:block;margin:5px 0 7px;\">{$user->getUser_login()}</a> {$this->htmlpurify($user->getSmall_bio(), 90, 0)}</td>";
                                if (Zend_Auth::getInstance()->getIdentity()) {
                                    if (Zend_Auth::getInstance()->getIdentity()->user_id == $this->user->user_id) {
                                        $following = true;
                                    } else {
                                        $user_model = new User_Model_UserMapper();
                                        $following = $user_model->isUserFollowingUser(Zend_Auth::getInstance()->getIdentity()->user_id, $user->getUser_id());
                                    }
                                    if ($following) {
                                        $output[] = "   <td style=\"width:150px\"><a style=\"margin:20px 0 0 0;\" href=\"{$this->url(array('user' => $user->getUser_login(), 'act' => 'unfollow'), 'user_follow_user')}\" data-user=\"{$user->getUser_login()}\" class=\"btn btn-primary unfllw_u_btn minusone\"><i class=\"icon-ok icon-white\"></i> Following</a></td>";
                                    } else {
                                        $output[] = "   <td style=\"width:150px\"><a style=\"margin:20px 0 0 0;\" href=\"{$this->url(array('user' => $user->getUser_login(), 'act' => 'follow'), 'user_follow_user')}\" data-user=\"{$user->getUser_login()}\" class=\"btn fllw_u_btn plusone\">Follow</a></td>";
                                    }
                                }
                                $output[] = "</tr>";
                            }
                            $output[] = "</tbody>";
                            $output[] = "</table>";
                            
                            $output[] = "<a class=\"ld_act\" style=\"text-align:center\" href=\"{$this->url(array('id' => $this->user->user_login), 'user_following')}?page=" . ($this->page + 1) . "\">Load more</a>";

                            echo implode("\n", $output);
                        }
                        ?>
                        
                        <div id="loading_more" style="height: 70px;margin: 0 auto;width: 70px;"></div>
                        
                    </div>
                    <div class="tab-pane" id="noticeboards">
                        <?php
                        if ($this->noticeboards) {
                            $output = array();
                            $output[] = "<table class=\"table\">";
                            $output[] = "<tbody>";
                            foreach ($this->noticeboards as $noticeboard) {
                                $following = false;
                                $output[] = "<tr>";
                                $output[] = "   <td>{$this->noticeboardhover($noticeboard['noticeboard_url'], 'suggest_n_fllw')} {$this->htmlpurify($noticeboard['noticeboard_tagline'])}</p></td>";
                                if (Zend_Auth::getInstance()->getIdentity()) {
                                    if (Zend_Auth::getInstance()->getIdentity()->user_id == $this->user->user_id) {
                                        $following = true;
                                    } else {
                                        $noticebard_model = new Noticeboard_Model_NoticeboardMapper();
                                        $following = $noticebard_model->isUserFollowingNoticeboard(Zend_Auth::getInstance()->getIdentity()->user_id, $noticeboard['noticeboard_url']);
                                    }
                                    if ($following) {
                                        $output[] = "   <td style=\"width:150px\"><a style=\"margin:0;float: right;\" href=\"{$this->url(array('domain' => $noticeboard['noticeboard_url'], 'act' => 'unfollow'), 'user_follow_noticeboard')}\" data-noticeboard=\"{$noticeboard['noticeboard_url']}\" class=\"btn btn-primary unfllw_n_btn minusone\"><i class=\"icon-ok icon-white\"></i> Following</a></td>";
                                    } else {
                                        $output[] = "   <td style=\"width:150px\"><a style=\"margin:0;float: right;\" href=\"{$this->url(array('domain' => $noticeboard['noticeboard_url'], 'act' => 'follow'), 'user_follow_noticeboard')}\" data-noticeboard=\"{$noticeboard['noticeboard_url']}\" class=\"btn fllw_n_btn plusone\">Follow</a></td>";
                                    }
                                }
                                $output[] = "</tr>";
                            }
                            $output[] = "</tbody>";
                            $output[] = "</table>";

                            echo implode("\n", $output);
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div> <!-- End: Top heading -->

<?php
$script = "
$(function(){

    $(window).hashchange( function(){
        $('ul.nav a[href=\"' + location.hash + '\"]').tab('show');
        window.scrollTo(0, 0);
        return false;
    });

    $(window).hashchange();

});
";
$this->headScript()->appendScript($script);
?>

<?php
if ($this->users) {
    $script = "
        var activateGlossyimages = function () {
            $('.glossy_thumbs img').each(function() {
                var imgClass = $(this).attr('class');
                $(this).wrap('<span class=\"image-wrap ' + imgClass + '\"/>');
                $(this).removeAttr('class');
            });
        }
        
        var loading = $('#loading_more');
        var act_page = 2;
        $('.ld_act').hide();
        var footer = $('footer'), opts = { offset: '100%' };
        footer.waypoint(function(event, direction) {
            loading.spin();
            footer.waypoint('remove');
            $.get($('.ld_act').attr('href')+'&jquery=1&page='+act_page, function(data) {
                data = $(data);
                data = data.find('table.user_data > tbody > tr');
                if(data.length === 0) {
                    $('table.user_data').after('<p style=\"text-align:center\"><strong>No more users to display.</strong></p>');
                    $('.ld_act').removeClass('ld_act').hide();
                    loading.spin(false);
                    return false;
                }
                loading.spin(false);
                $('table.user_data > tbody:last').append(data);
                $('abbr.timeago').timeago();
                activateGlossyimages();
                act_page++;
                footer.waypoint(opts);
            });
        }, opts);
    ";
    $this->headScript()->appendScript($script);
}
?>