<?php

function is_valid_callback($subject) {
    $identifier_syntax = '/^[$_\p{L}][$_\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{200C}\x{200D}]*+$/u';

    $reserved_words = array('break', 'do', 'instanceof', 'typeof', 'case',
        'else', 'new', 'var', 'catch', 'finally', 'return', 'void', 'continue',
        'for', 'switch', 'while', 'debugger', 'function', 'this', 'with',
        'default', 'if', 'throw', 'delete', 'in', 'try', 'class', 'enum',
        'extends', 'super', 'const', 'export', 'import', 'implements', 'let',
        'private', 'public', 'yield', 'interface', 'package', 'protected',
        'static', 'null', 'true', 'false');

    return preg_match($identifier_syntax, $subject) && !in_array(mb_strtolower($subject, 'UTF-8'), $reserved_words);
}

$output = array();

$output[] = "<div style=\"margin:10px 0;\">";
$output[] = "    <div class=\"row\">";
$output[] = "        <div class=\"span1\" style=\"width:100px\">";
$output[] = $this->profilepicture($this->user->user_login, 'medium', 1, 'thumbnail');
$output[] = "        </div>";
$output[] = "        <div class=\"span3\" style=\"width:220px\">";
$output[] = "           <h3 style=\"margin-bottom:3px;\"><a href=\"{$this->url(array('id' => $this->user->user_login), 'user_view')}\">{$this->user->display_name}</a></h3>";
if(Zend_Auth::getInstance()->getIdentity()) {
    if(Zend_Auth::getInstance()->getIdentity()->role == 'admin') {
        $output[] = "<h3>Email: {$this->user->user_email}</h3>";
    }
}
$output[] = "            <div class=\"hvr_bio\">";
$output[] = $this->htmlpurify($this->small_bio, 140);
$output[] = "            </div>";
$output[] = "            <p>Following <b>".number_format($this->user_following_count)."</b> | Followers <b>".number_format($this->user_followers_count)."</b></p>";
if (Zend_Auth::getInstance()->getIdentity()) {
    $output[] = "            <div class=\"hvr_btn_float\">";
    if ($this->is_current_user_following) {
        $output[] = "               <a style=\"float:right\" href=\"{$this->url(array('user' => $this->user->user_login, 'act' => 'unfollow'), 'user_follow_user')}?redirect={$this->url()}\" data-user=\"{$this->user->user_login}\" class=\"btn btn-primary unfllw_u_btn\"><i class=\"icon-ok icon-white\"></i> Following</a>";
    } else {
        $output[] = "               <a style=\"float:right\" href=\"{$this->url(array('user' => $this->user->user_login, 'act' => 'follow'), 'user_follow_user')}?redirect={$this->url()}\" data-user=\"{$this->user->user_login}\" class=\"btn fllw_u_btn\">Follow</a>";
    }
    $output[] = "          </div>";
}
$output[] = "     </div>";
$output[] = "   </div>";
$output[] = "</div>";

$data = array();
$data['output'] = implode("\n", $output);

if (is_valid_callback($_GET['callback'])) {
    header('content-type: application/json; charset=utf-8');
    echo $_GET['callback'] . '(' . json_encode($data) . ')';
} else {
    header('status: 400 Bad Request', true, 400);
}
?>