<?php
$this->headTitle()->prepend(ucwords($this->user->user_login));
?>

<div class="row"> <!-- Top heading -->
    <div class="span3">

        <?= $this->render('_viewsidebar.phtml') ?>

    </div>

    <div class="span9">

        <h1 style="font-size: 45px; margin-bottom: 0.5em;"><?= $this->user->user_login ?> <small><?= $this->escape($this->user->display_name) ?></small></h1>
        
        <?php
        if(Zend_Auth::getInstance()->getIdentity()) {
            if(Zend_Auth::getInstance()->getIdentity()->role == 'admin') {
                echo "<h3>Email: {$this->user->user_email}</h3>";
            }
        }
        ?>
        
        <!--
        <?php $this->headLink()->appendAlternate($this->rssUrl, 'application/rss+xml', 'RSS Feed'); ?>
        -->

        <div class="subnav">
            <ul class="nav nav-pills">
                <li style="float:right"><a href="<?= $this->rssUrl ?>"><i class="icon-fire"></i> RSS</a></li>
            </ul>
        </div>

        <div style="padding:15px;">
            
        </div>

    </div>

</div> <!-- End: Top heading -->