<?php
$this->headTitle()->prepend(ucwords($this->user->user_login));
$this->headTitle()->prepend('Following');
?>

<style>
    .table tr:first-child td { border-top: none; }
</style>

<div class="row"> <!-- Top heading -->
    <div class="span3">

        <?= $this->render('_viewsidebar.phtml') ?>

    </div>

    <div class="span9">

        <h1 style="font-size: 45px; margin-bottom: 0.5em;"><?= $this->user->user_login ?> <small><?= $this->escape($this->user->display_name) ?></small></h1>

        <div class="subnav">
            <ul class="nav nav-pills">
                <li><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_view') ?>">Recent Activity</a></li>
                <li><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_followers') ?>"><b><?= $this->user_followers_count ?></b> followers</a></li>
                <li><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_following') ?>">following <b><?= $this->total_following_count ?></b></a></li>
                <li class="active"><a href="<?= $this->url(array('id' => $this->user->user_login), 'user_noticeboards') ?>"><b><?= $this->user_noticeboard_count ?></b> noticeboards</a></li>
            </ul>
        </div>

        <hr class="space">

        <?php
        if ($this->user_admin_noticeboard) {
            $output = array();
            $output[] = "<table class=\"table\">";
            $output[] = "<tbody>";
            foreach ($this->user_admin_noticeboard as $noticeboard) {
                $output[] = "<tr>";
                $output[] = "   <td>{$this->noticeboardhover($noticeboard['noticeboard_url'], 'suggest_n_fllw')} {$this->htmlpurify($noticeboard['noticeboard_tagline'])}</p></td>";
                if (Zend_Auth::getInstance()->getIdentity()) {
                    $noticebard_model = new Noticeboard_Model_NoticeboardMapper();
                    $following = $noticebard_model->isUserFollowingNoticeboard(Zend_Auth::getInstance()->getIdentity()->user_id, $noticeboard['noticeboard_url']);
                    if ($following) {
                        $output[] = "   <td style=\"width:150px\"><a style=\"margin:0;float: right;\" href=\"{$this->url(array('domain' => $noticeboard['noticeboard_url'], 'act' => 'unfollow'), 'user_follow_noticeboard')}\" data-noticeboard=\"{$noticeboard['noticeboard_url']}\" class=\"btn btn-primary unfllw_n_btn minusone\"><i class=\"icon-ok icon-white\"></i> Following</a></td>";
                    } else {
                        $output[] = "   <td style=\"width:150px\"><a style=\"margin:0;float: right;\" href=\"{$this->url(array('domain' => $noticeboard['noticeboard_url'], 'act' => 'follow'), 'user_follow_noticeboard')}\" data-noticeboard=\"{$noticeboard['noticeboard_url']}\" class=\"btn fllw_n_btn plusone\">Follow</a></td>";
                    }
                }
                $output[] = "</tr>";
            }
            $output[] = "</tbody>";
            $output[] = "</table>";

            echo implode("\n", $output);
        }
        ?>

    </div>

</div> <!-- End: Top heading -->