<?php
$this->headTitle()->prepend(ucwords($this->user->user_login));
$this->headTitle()->prepend('Messages');
?>

        
<a href="<?= $this->url(array('id' => $this->user->user_login), 'user_inbox') ?>" class="btn" style="float:right">Back to messages</a>

<h4>In this conversation: <?= $this->information ?></h4>

<hr>

<?= $this->usermessagethread($this->messages); ?>

<hr class="space">

<div id="thread_comment">
    <h3>Reply to this thread</h3>
    <?= $this->form ?>
</div>