<?php
$title = "Community Activity ";
if (!$this->address) {
    $title .= "everywhere";
} else {
    $title .= "within {$this->radius} {$this->distance_type} of <span class=\"location_pop\">{$this->address}</span>";
}
$this->headTitle()->prepend(strip_tags($title));
?>
<h2 class="hd-tl"><?= $title ?></h2>

<ul class="nav nav-tabs">
    <li><a href="<?= $this->url(array(), 'user_home') ?>">All community members</a></li>
    <li class="active"><a href="<?= $this->url(array(), 'user_activity') ?>">Activity</a></li>
</ul>

<br>

<div class="row">
    <div class="span9">

        <div style="float:left;width:100%">
            <div style="padding:10px;">
                <?= $this->useractivity($this->contentitems, $this->url(array(), 'user_activity')); ?>
            </div>
        </div>

        <div id="loading_more" style="height: 70px;margin: 0 auto;width: 70px;"></div>

    </div>

    <div class="span3">
        <h3>Most Active People</h3>
        <ul class="thumbs medium">
            <?php
            if($this->activeusers) {
                foreach ($this->activeusers as $user) {
                    echo "<li>{$this->profilepicture($user, 'medium', 1)}</li>";
                }
            }
            ?>
        </ul>
    </div>
</div>

<?php
$script = "
    var loading = $('#loading_more');
    var act_page = 2;
    $('.ld_act').hide();
    var footer = $('footer'), opts = { offset: '100%' };
    footer.waypoint(function(event, direction) {
        loading.spin();
        footer.waypoint('remove');
        $.get($('.ld_act').attr('href')+'?jquery=1&page='+act_page, function(data) {
            if(data.length === 0) {
                $('.ld_act').parent().html('<strong>No more posts to display.</strong>');
                $('.ld_act').removeClass('ld_act');
                loading.spin(false);
                return false;
            }
            loading.spin(false);
            $('.activity_items').append(data);
            $('abbr.timeago').timeago();
            act_page++;
            footer.waypoint(opts);
        });
    }, opts);
";
$this->headScript()->appendScript($script);
?>