<?php
$elem = $this->element;
$elemName = $elem->getName();
$values = $elem->getValue();

$class = "";
$errors = "";
if ($this->element->hasErrors()) {
    $errors = "<p class=\"help-block\">{$this->formErrors($this->element->getMessages())}</p>";
    $class = " error";
}

$checked = '';
if($elem->checked) {
    $checked = "checked=\"checked\"";
}
?>

<label class="checkbox" style="margin:0 10px 30px;font-size: 14px;">
    <input type="checkbox" value="<?= $elem->getValue() ?>" id="<?= $elem->getId() ?>" name="<?= $elem->getId() ?>" <?= $checked ?>>
    <?= $elem->getLabel() ?>
</label>
<?= $errors ?>