<?php
$title = "Follow Users";
$this->headTitle()->prepend(strip_tags($title));
?>
<h1 class="hd-tl" style="text-align: center;"><?= $title ?></h1>

<div class="row">
    <div class="span7 offset1">
        <ul class="nav nav-tabs">
            <li><a href="<?= $this->url(array('section' => 'most-followed'), 'user_suggest_users') ?>">Most Followed</a></li>
            <li class="active"><a href="#">Topic or Location</a></li>
            <li><a href="<?= $this->url(array('section' => 'people'), 'user_suggest_users') ?>">People</a></li>
        </ul>

        <br>
        
        
        <form id="user_name_form" class="well form-search">
            <input type="text" placeholder="search for a topic or location" class="span4 search-query" id="user_name_q" autocomplete="off">
            <button class="btn" type="submit">Search</button>
            <p class="help-block suggst_q">Popular searches: <a href="#">crime london</a>, <a href="#">manchester</a>, <a href="#">music liverpool</a></p>
        </form>
        
        <table class="table user_data">
            <tbody>

            </tbody>
        </table>
        
        <?php
        if($this->users_table) {
            echo $this->users_table;
        }
        ?>
        <div class="loading_more" style="height: 70px;margin: 20px auto;width: 70px;"></div>

    </div>

    <div class="span4">

        <div class="fllw_y">
            <div class="fllw_inner">
                <h3>Quick tips</h3>
                <ul>
                    <li>Click the follow button to add a person to your Stream</li>
                    <li>Discover users that post about topics and places that interest you. Click the 'topics' tab.</li>
                    <li>Find n0tice users you already know. Click the 'username' tab.</li>
                </ul>

            </div>
        </div>

    </div>
</div>

<style>
    .table tr:first-child td { border-top: none; }
</style>

<?php
$script = "
    var loading_more = $('.loading_more');
    var act_page = 2;

    var infinite_scroll = false;

    $('#user_name_form').submit(function() {
        var n = $('#user_name_q').val();
        if(n.length !== 0) {
            searchNameAjax(n);
        }
        return false;
    });

    $('.suggst_q a').live('click', function() {
        var query = $(this).html();
        $('#user_name_q').val(query);
        searchNameAjax(query);
        return false;
    });

    
    function searchNameAjax(q) {
        loading_more.spin();
        $('table.user_data > tbody').html('');
        $('p.no_more').remove();
        $.get('{$this->url(array('section' => 'topic'), 'user_suggest_users')}?page=1&name='+q, function(data) {
            data = $(data);
            data = data.find('table.user_data > tbody > tr');
            if(data.length === 0) {
                $('table.user_data').before('<p class=\"no_more\" style=\"text-align:center\"><strong>No results to display.</strong></p>');
                loading_more.spin(false);
                infinite_scroll = false;
                return false;
            }
            $('table.user_data > tbody').html(data);
            loading_more.spin(false);
            infinite_scroll = '{$this->url(array('section' => 'topic'), 'user_suggest_users')}?page=2&name='+q;
            activateGlossyimages();
            return false;
        });
    }
        
    var activateGlossyimages = function () {
        $('.glossy_thumbs img').each(function() {
            var imgClass = $(this).attr('class');
            $(this).wrap('<span class=\"image-wrap ' + imgClass + '\"/>');
            $(this).removeAttr('class');
        });
    }
";
$this->headScript()->appendScript($script);
?>