<?php
$title = "Follow Noticeboards";
$this->headTitle()->prepend(strip_tags($title));
?>
<h1 class="hd-tl" style="text-align: center;"><?= $title ?></h1>

<div class="row">
    <div class="span6 offset1">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#fl_mp" data-toggle="tab">Most Popular</a></li>
            <li><a href="#fl_s" data-toggle="tab">Topic or Location</a></li>
            <li><a href="#fl_n" data-toggle="tab">Name</a></li>
        </ul>

        <br>

        <div class="tab-content">
            <div class="tab-pane active" id="fl_mp">
                <?= $this->noticeboards_table ?>
            </div>
            <div class="tab-pane" id="fl_s">
                <form id="user_search_form" class="well form-search">
                    <input type="text" placeholder="search for a topic or location" class="span4 search-query" id="user_search_q" autocomplete="off">
                    <button class="btn" type="submit">Search</button>
                    <p class="help-block suggst_q">Popular searches: <a href="#">graffiti</a>, <a href="#">crafts</a>, <a href="#">music liverpool</a></p>
                </form>

                <div class="loading_more hide" style="height: 70px;margin: 20px auto;width: 70px;"></div>

                <div id="user_search_ajax">

                </div>

            </div>

            <div class="tab-pane" id="fl_n">
                <form id="user_name_form" class="well form-search">
                    <input type="text" placeholder="search by name" class="span4 search-query" id="user_name_q" autocomplete="off">
                    <button class="btn" type="submit">Search</button>
                </form>

                <div class="loading_more hide" style="height: 70px;margin: 20px auto;width: 70px;"></div>

                <div id="user_name_ajax">

                </div>

            </div>

        </div>
    </div>

    <div class="span5">
        <div class="fllw_y">
            <div class="fllw_inner">
                <h3>Quick tips</h3>
                <ul>
                    <li>Click the follow button to add a noticeboard to your Stream.</li>
                    <li>Discover noticeboards that cover topics and places that interest you. Click the 'topics' tab.</li>
                    <li>Find noticeboards you already know. Click the 'name' tab.</li>
                </ul>
            </div>
        </div>

    </div>
</div>

<style>
    .table tr:first-child td { border-top: none; }
</style>

<?php
$script = "
    var url = window.location.pathname;
    var loading = $('.loading_more');
    
    $('#user_search_form').submit(function() {
        var q = $('#user_search_q').val();
        if(q.length !== 0) {
            searchAjax(q);
        }
        return false;
    });
    $('.suggst_q a').live('click', function() {
        var query = $(this).html();
        $('#user_search_q').val(query);
        searchAjax(query);
        return false;
    });
    
    function searchAjax(q) {
        $('#user_search_ajax').html('');
        loading.spin().show();
        $.get(url+'?jquery=1&q='+q, function(data) {
            if(data.length === 0) {
                $('#user_search_ajax').html('<p>No results sorry.</p>');
                loading.spin(false).hide();
                return false;
            }
            loading.spin(false).hide();
            $('#user_search_ajax').html(data);
        });
    }
    
    $('#user_name_form').submit(function() {
        var n = $('#user_name_q').val();
        if(n.length !== 0) {
            searchNameAjax(n);
        }
        return false;
    });
    function searchNameAjax(q) {
        $('#user_name_ajax').html('');
        loading.spin().show();
        $.get(url+'?jquery=1&name='+q, function(data) {
            if(data.length === 0) {
                $('#user_name_ajax').html('<p>No results sorry.</p>');
                loading.spin(false).hide();
                return false;
            }
            loading.spin(false).hide();
            $('#user_name_ajax').html(data);
        });
    }
";
$this->headScript()->appendScript($script);
?>