<?php
$this->headTitle()->prepend(ucwords($this->user->user_login));
$this->headTitle()->prepend('Edit');
?>

<hr class="space">

<div class="row">

    <?= $this->usersettingsmenu($this->user->user_login, 'invite') ?>

    <div class="span10">
        <div class="u_e_i">
            <a href="<?= $this->url(array('id' => $this->user->user_login), 'user_view') ?>" class="btn" style="float:right">Back to profile</a>
            <h2><?= $this->title ?></h2>

            <ul class="nav nav-tabs" style="font-size: 14px;">
                <li><a href="<?= $this->url(array('id' => $this->user->user_login, 'service' => ''), 'user_edit_invite') ?>">via Email</a></li>
                <li><a href="<?= $this->url(array('id' => $this->user->user_login, 'service' => 'facebook'), 'user_edit_invite') ?>">via Facebook</a></li>
                <li class="active"><a href="<?= $this->url(array('id' => $this->user->user_login, 'service' => 'twitter'), 'user_edit_invite') ?>">via Twitter</a></li>
            </ul>

            <?php
            $output = array();
            if (!$this->twitter) {
                $output[] = "<p class=\"alert\">Connect your Twitter account to activate this feature. Click on the button below.</p>";
                $output[] = "<a href=\"{$this->url(array('id' => $this->user->user_login, 'service' => 'twitter'), 'user_edit_add_social')}\" class=\"tw s_auth\">";
                $output[] = "    <div class=\"ic\"></div>";
                $output[] = "    <span>Link with Twitter</span>";
                $output[] = "</a>";
            } else {
                $output[] = "<h3>Twitter Friends</h3>";
                $output[] = "<p class=\"alert\">Click on the names below to invite them to n0tice or <a target=\"_blank\" href=\"http://twitter.com/?status=".urlencode("Join me on http://www.n0tice.com")."\">write a tweet to all your followers here</a>.</p>";
                $output[] = $this->userinvitetw($this->friends, $this->registered_users);
                $output[] = "<a class=\"btn btn-load-more-invites\" style=\"clear:both;margin-top:10px;text-align:center;display:block;width:94%\" href=\"{$this->url(array('id' => $this->user->user_login, 'service' => 'twitter'), 'user_edit_invite')}\" data-page=\"".($this->page + 1)."\">More</a>";
                
                $script = "
                    var loading = $('#loading_more');
                    var act_page = 2;
                    var btn = $('.btn-load-more-invites');
                    var footer = $('footer'), opts = { offset: '100%' };

                    btn.hide();
                    footer.waypoint(function(event, direction) {
                        loading.spin();
                        footer.waypoint('remove');
                        $.get($('.btn-load-more-invites').attr('href')+'?page='+act_page, function(data) {
                            if(data.length === 0) {
                                btn.before('<hr class=\"space\"><p><strong>No more people to display.</strong></p>');
                                btn.removeClass('btn-load-more-invites');
                                loading.spin(false);
                                return false;
                            }
                            loading.spin(false);
                            btn.before(data);
                            act_page++;
                            footer.waypoint(opts);
                        });
                    }, opts);
                ";
                $this->headScript()->appendScript($script);
            }
            echo implode("\n", $output);
            ?>
            
            <hr class="space">
            <div id="loading_more" style="height: 70px;margin: 0 auto;width: 70px;"></div>

        </div>
    </div>
</div>