<?php
if (Zend_Auth::getInstance()->getIdentity()) {
    echo $this->render('_navbar.phtml');
}
?>
<header>
    <div class="container">
        <div class="row">
            <div class="span4">
                <a href="<?= $this->url(array(), 'home') ?>" class="logo"><?= $this->sitename ?></a>
            </div>
            <div class="span8 main-nav">
                <?= $this->render('_navigation.phtml') ?>
            </div>
        </div>
    </div>
</header>