<?php
$output = array();
$output[] = "<ul>";
if(Zend_Auth::getInstance()->getIdentity()) {
    $output[] = "<li><a href=\"#\">Challenges</a></li>";
    $output[] = "<li><a href=\"#\">Explore</a></li>";
    $output[] = "<li><a href=\"#\">Community</a></li>";
} else {
    $output[] = "<li><a href=\"{$this->url(array(), 'auth_login')}\">Login</a></li>";
    $output[] = "<li class=\"signup\"><a href=\"{$this->url(array(), 'auth_signup')}\">Signup</a></li>";
}
$output[] = "</ul>";
echo implode("\n", $output);