<?php
$user = Zend_Auth::getInstance()->getIdentity();
?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <ul class="nav">
                <li><a href="<?= $this->url(array(), 'home') ?>" class="nav-home"><i class="icon-home"></i></a></li>
            </ul>
            <ul class="nav pull-right">
                <li class="divider-vertical"></li>
                <li><a href="<?= $this->url(array('id'=>$user->user_login, 'page' => 0), 'user_inbox') ?>"><i class="icon-envelope"></i></a></li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-link" style="background-image:url('<?= $this->profilepicture($user->user_login, 'small', 'src') ?>')" data-toggle="dropdown"><?= $user->display_name ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url(array('id'=>$user->user_login), 'user_view') ?>">Profile</a></li>
                        <li><a href="<?= $this->url(array('id'=>$user->user_login, 'page' => 0), 'user_inbox') ?>">Messages</a></li>
                        <li><a href="<?= $this->url(array('id'=>$user->user_login, 'edit' => 'account'), 'user_edit') ?>">Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="<?= $this->url(array(), 'auth_logout') ?>"><i class="icon-signout"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-search pull-right">
                <input type="text" class="search-query span2" placeholder="Search">
            </form>
        </div>
    </div>
</div>
<style>
    /* Responsive rules
    */
    body {
        padding-top: 40px;
    }
</style>